// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowButton: typeof import('./src/components/base/arrowButton.vue')['default']
    Book: typeof import('./src/components/home/book.vue')['default']
    Chart: typeof import('./src/components/chart.vue')['default']
    ColorTriangle: typeof import('./src/components/case/ColorTriangle.vue')['default']
    DomMatrix: typeof import('./src/components/case/DomMatrix.vue')['default']
    Elsewhere: typeof import('./src/components/blog/elsewhere.vue')['default']
    Grid: typeof import('./src/components/grid.vue')['default']
    Header: typeof import('./src/components/base/header.vue')['default']
    Introduce: typeof import('./src/components/home/introduce.vue')['default']
    KnowledgeGraph: typeof import('./src/components/sugar/knowledgeGraph.vue')['default']
    MagicCard: typeof import('./src/components/case/MagicCard.vue')['default']
    MdPreview: typeof import('./src/components/base/mdPreview.vue')['default']
    Music: typeof import('./src/components/base/music.vue')['default']
    MutiLayer: typeof import('./src/components/case/MutiLayer.vue')['default']
    PokerCard: typeof import('./src/components/sugar/pokerCard.vue')['default']
    PowerBalance: typeof import('./src/components/sugar/powerBalance.vue')['default']
    Profile: typeof import('./src/components/home/profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningBall: typeof import('./src/components/case/RunningBall.vue')['default']
    SalaryGrowth: typeof import('./src/components/sugar/salaryGrowth.vue')['default']
    SkillShow: typeof import('./src/components/sugar/skillShow.vue')['default']
    Smoke: typeof import('./src/components/base/smoke.vue')['default']
    StarNight: typeof import('./src/components/case/StarNight.vue')['default']
    Thunderstorm: typeof import('./src/components/case/Thunderstorm.vue')['default']
    Timeline: typeof import('./src/components/home/timeline.vue')['default']
    VolumeSound: typeof import('./src/components/case/VolumeSound.vue')['default']
  }
}
